import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Provider from './Provider'
import { Analytics } from '@vercel/analytics/react';
import Navbar from '@/app/components/Navbar'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Provider>
        <body className={`${nunito.className} antialiased container-full mx-auto bg-jada-green-600`}>
          <Navbar/>
          {children}
        <Analytics />
        </body>
      </Provider>
    </html>
  )
}
